- name: Setup vars
  set_fact:
    container_name: sabesp_selenium
    image_name: selenium-test

- name: Start container fresh
  docker_container:
    name: "{{ container_name }}"
    state: absent

- name: Get SABESP bills
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    state: started
    command: "python /run.py '{{ item.location }}' '{{ item.rgi }}' '{{ owner }}'"
    detach: false
    volumes:
      - ../roles/sabesp/tasks/sabesp.py:/run.py
  register: output
  loop: "{{ rgis }}"

- name: Flatten results
  set_fact:
    output_flatten: "{{ output.results | map(attribute='ansible_facts.docker_container.Output') | list | join('\n') }}"

- name: Setup results
  vars:
    element: "{{ item.split(';') }}"
  set_fact:
    sabesp_bills: "{{ sabesp_bills|default([]) + [{ 'location': element[0], 'month': element[1], 'due_date': element[2], 'value': element[3] }] }}"
  loop: "{{ output_flatten.split('\n') }}"
  when: item != ''

- name: Display bills
  debug:
    var: sabesp_bills

- name: Remove container
  docker_container:
    name: "{{ container_name }}"
    state: absent
